# Generated by Django 3.1.14 on 2022-03-01 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpush', '0003_subscriptioninfo_user_agent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='pushinformation',
            options={'verbose_name': 'Push information', 'verbose_name_plural': 'Pushes information'},
        ),
        migrations.AlterModelOptions(
            name='subscriptioninfo',
            options={'verbose_name': 'Subscription info', 'verbose_name_plural': 'Subscriptions info'},
        ),
    ]