# Generated by Django 3.1.14 on 2022-03-01 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpush', '0004_auto_20220831_1500'),
        ('webpush', '0004_set_name'),
    ]

