# Generated by Django 4.2.9 on 2024-02-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webpush", "0005_merge_migrations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="pushinformation",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="subscriptioninfo",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]